"""Purge KB contents back to a clean, scaffolded state.

Removes ingested/authored content while leaving the machinery intact:
`manifest.yaml`, `AGENTS.md`, `tools/`, `_schema/`, and `_templates/` are
never touched — so `scaffold` is not needed afterwards; the KB is simply empty.

Dry-run by default: prints exactly what *would* be removed and returns without
changing anything. Pass `--yes` to actually apply the purge.

Scopes (default: everything):
  (none)    raw sources + wiki pages + regenerated views
  --raw     only raw/ source documents
  --wiki    only wiki pages + regenerated views

Usage: python tools/kb.py purge [--raw] [--wiki] [--yes]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from _common import KB_ROOT, load_manifest


def _raw_files(m: dict) -> list[Path]:
    root = KB_ROOT / m["paths"]["raw"]
    return [p for p in sorted(root.rglob("*")) if p.is_file()]


def _wiki_page_files(m: dict) -> list[Path]:
    wiki = KB_ROOT / m["paths"]["wiki"]
    files: list[Path] = []
    for tspec in m["page_types"].values():
        files += sorted((wiki / tspec["folder"]).glob("*.md"))
    graph = wiki / "_graph.md"  # generated view; regenerated by _reset_views
    if graph.exists():
        files.append(graph)
    return files


def _reset_views(m: dict) -> None:
    """Regenerate the derived views from the (now-empty) wiki: index.md marker
    blocks reset to placeholders, wiki/_graph.md and mkdocs.yml rebuilt."""
    import kb   # reuse the canonical index rebuild (marker-block regex)
    import viz  # reuse the canonical graph + mkdocs generation
    kb.cmd_index()
    viz.main()


def run(scope: str = "all", yes: bool = False) -> int:
    m = load_manifest()
    targets: list[Path] = []
    if scope in ("all", "raw"):
        targets += _raw_files(m)
    if scope in ("all", "wiki"):
        targets += _wiki_page_files(m)
    reset_views = scope in ("all", "wiki")

    if not targets and not reset_views:
        print("nothing to purge.")
        return 0

    print(f"purge scope: {scope}")
    verb = "removing" if yes else "would remove"
    for p in targets:
        print(f"  {verb}: {p.relative_to(KB_ROOT)}")
    if reset_views:
        print(f"  {'resetting' if yes else 'would reset'} views: "
              f"{m['paths']['index']}, {m['paths']['wiki']}/_graph.md, mkdocs.yml")

    if not yes:
        print(f"\nDry run — {len(targets)} file(s) would be removed. "
              "Re-run with --yes to apply.")
        return 0

    for p in targets:
        p.unlink()
    if reset_views:
        _reset_views(m)
    print(f"\npurged {len(targets)} file(s); the KB is back to a clean state.")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--raw", action="store_true", help="purge only raw/ sources")
    ap.add_argument("--wiki", action="store_true", help="purge only wiki pages + views")
    ap.add_argument("--yes", action="store_true", help="apply (default is dry-run)")
    a = ap.parse_args()
    # Neither or both flags means "everything".
    chosen = "all" if a.raw == a.wiki else ("raw" if a.raw else "wiki")
    sys.exit(run(scope=chosen, yes=a.yes))
