"""Visualization layer: generate a static-site config + a Mermaid link graph.

No server or infra needed to build. Emits:
  - mkdocs.yml         (MkDocs Material config; nav derived from wiki/)
  - wiki/index.md      (site homepage: a Mermaid graph of [[wikilinks]], nodes
                        colored by confidence band — MkDocs serves it at the
                        site root)

`mkdocs build` then produces a searchable, browsable HTML site; the publish
GitHub Action deploys it to Pages. Everything is regenerated from files, so the
viz never drifts from the source of truth.
"""
from __future__ import annotations

from pathlib import Path

from _common import KB_ROOT, confidence_band, iter_pages, load_manifest


# How each page type is drawn. `shape` is a (prefix, suffix) pair wrapping the
# node label so the type is legible from the silhouette alone: concepts are
# rounded, entities are stadiums, sources are document/parallelograms.
TYPE_SHAPE = {
    "concept": ("(", ")"),
    "entity": ("([", "])"),
    "source": ("[/", "/]"),
}
TYPE_LABEL = {"concept": "concept", "entity": "entity", "source": "source"}


def _safe(node_id: str) -> str:
    return node_id.replace("-", "_")


def _neighbours(pages, ids) -> dict[str, set[str]]:
    """Undirected connectivity: for each page, the set of distinct other pages
    it links to or is linked from. This is the `count` shown on each node, so
    we never have to draw the individual link lines."""
    nb: dict[str, set[str]] = {p.id: set() for p in pages}
    for p in pages:
        for tgt in p.links():
            if tgt in ids and tgt != p.id:
                nb[p.id].add(tgt)
                nb[tgt].add(p.id)
    return nb


def build_graph(m: dict) -> str:
    """A line-free overview: one node per page, labelled with its connection
    count and coloured by confidence. Relationships live in the table below —
    the graph deliberately draws no edges so it never turns into a hairball."""
    pages = list(iter_pages(m))
    band_color = {b["label"]: b["color"] for b in m["confidence_policy"]["bands"]}
    ids = {p.id for p in pages}
    nb = _neighbours(pages, ids)

    lines = ["```mermaid", "graph LR"]
    styles: list[str] = []
    for p in sorted(pages, key=lambda p: (-len(nb[p.id]), p.id)):
        conf = float(p.frontmatter.get("confidence", 0.0) or 0.0)
        band = confidence_band(conf, m)
        title = str(p.frontmatter.get("title", p.id)).replace('"', "'")
        ptype = TYPE_LABEL.get(p.type, p.type or "page")
        pre, suf = TYPE_SHAPE.get(p.type, ("[", "]"))
        sid = _safe(p.id)
        count = len(nb[p.id])
        label = (f'{title}<br/><small>{ptype} · {conf} {band}</small>'
                 f'<br/><b>{count}🔗</b>')
        lines.append(f'  {sid}{pre}"{label}"{suf}')
        styles.append(f'  style {sid} fill:{band_color[band]}22,'
                      f'stroke:{band_color[band]},stroke-width:2px,color:#212529')
    lines.extend(styles)
    lines.append("```")
    return "\n".join(lines)


def build_table(m: dict) -> str:
    """Line-free relationship view: each page and what it links to, so the
    connections are legible without any edges drawn on the graph."""
    pages = list(iter_pages(m))
    ids = {p.id for p in pages}
    nb = _neighbours(pages, ids)
    rows = ["| Page | Type | Confidence | 🔗 | Connects to |",
            "| --- | --- | --- | --- | --- |"]
    for p in sorted(pages, key=lambda p: (-len(nb[p.id]), p.id)):
        conf = float(p.frontmatter.get("confidence", 0.0) or 0.0)
        band = confidence_band(conf, m)
        title = str(p.frontmatter.get("title", p.id))
        ptype = TYPE_LABEL.get(p.type, p.type or "page")
        links = ", ".join(f"`{t}`" for t in sorted(nb[p.id])) or "—"
        rows.append(f"| **{title}** | {ptype} | {conf} {band} | "
                    f"{len(nb[p.id])} | {links} |")
    return "\n".join(rows)


def build_mkdocs(m: dict) -> str:
    wiki = KB_ROOT / m["paths"]["wiki"]
    # Enumerate real files so `mkdocs build --strict` never sees an unlisted page.
    # index.md is the homepage MkDocs serves at the site root.
    nav = ["  - Overview: index.md"]
    for tspec in m["page_types"].values():
        folder = tspec["folder"]
        files = sorted((wiki / folder).glob("*.md"))
        if not files:
            continue
        nav.append(f"  - {folder.capitalize()}:")
        for f in files:
            nav.append(f"      - {f.stem}: {folder}/{f.name}")
    return f"""# GENERATED by tools/viz.py from manifest.yaml. Do not hand-edit.
site_name: {m['name']!r}
site_description: {m['description'].strip()!r}
docs_dir: wiki
theme:
  name: material
  features: [navigation.instant, navigation.top, search.suggest, content.code.copy]
  palette:
    - scheme: default
      toggle: {{icon: material/brightness-7, name: dark}}
    - scheme: slate
      toggle: {{icon: material/brightness-4, name: light}}
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
nav:
{chr(10).join(nav)}
"""


def main() -> int:
    m = load_manifest()
    # The homepage (site root) is the knowledge graph itself.
    home_path = KB_ROOT / m["paths"]["wiki"] / "index.md"
    intro = (
        "---\ntitle: Knowledge Graph\n---\n\n# Knowledge Graph\n\n"
        "Every page in the wiki at a glance — no tangle of link lines. "
        "Each card reads as:\n\n"
        "- **Shape = type** — `(concept)` rounded, `([entity])` stadium, "
        "`[/source/]` document.\n"
        "- **Colour = confidence** — green `high` (≥0.75), orange `medium` "
        "(≥0.45), red `low`; the score sits under the title.\n"
        "- **`N🔗` = connections** — how many other pages this one is linked "
        "to. Cards are ordered by that count, so the hubs come first.\n\n"
        "The exact **who-links-to-whom** is in the table below the graph, "
        "so the relationships stay readable without drawing every edge.\n\n"
        "Regenerate after any content change with `python tools/kb.py viz`.\n\n"
    )
    body = build_graph(m) + "\n\n## Connections\n\n" + build_table(m) + "\n"
    home_path.write_text(intro + body)
    print(f"generated {home_path.relative_to(KB_ROOT)}")
    mk = KB_ROOT / "mkdocs.yml"
    mk.write_text(build_mkdocs(m))
    print(f"generated {mk.relative_to(KB_ROOT)}")
    print("build the site with:  cd .asdlc/knowledge && mkdocs build")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
