"""Visualization layer: generate a static-site config + a Mermaid link graph.

No server or infra needed to build. Emits:
  - mkdocs.yml         (MkDocs Material config; nav derived from wiki/)
  - wiki/index.md      (site homepage: a Mermaid graph of [[wikilinks]], nodes
                        colored by confidence band — MkDocs serves it at the
                        site root)

`mkdocs build` then produces a searchable, browsable HTML site; the publish
GitHub Action deploys it to Pages. Everything is regenerated from files, so the
viz never drifts from the source of truth.
"""
from __future__ import annotations

from pathlib import Path

from _common import KB_ROOT, confidence_band, iter_pages, load_manifest


def build_graph(m: dict) -> str:
    pages = list(iter_pages(m))
    band_color = {b["label"]: b["color"] for b in m["confidence_policy"]["bands"]}
    lines = ["```mermaid", "graph LR"]
    for p in pages:
        conf = p.frontmatter.get("confidence", 0.0) or 0.0
        band = confidence_band(float(conf), m)
        label = p.frontmatter.get("title", p.id).replace('"', "'")
        lines.append(f'  {p.id.replace("-", "_")}["{label}<br/>{conf} · {band}"]')
        lines.append(f'  style {p.id.replace("-", "_")} fill:{band_color[band]}22,'
                     f'stroke:{band_color[band]}')
    seen = set()
    ids = {p.id for p in pages}
    for p in pages:
        for tgt in p.links():
            if tgt in ids and (p.id, tgt) not in seen:
                seen.add((p.id, tgt))
                lines.append(f'  {p.id.replace("-", "_")} --> {tgt.replace("-", "_")}')
    lines.append("```")
    return "\n".join(lines)


def build_mkdocs(m: dict) -> str:
    wiki = KB_ROOT / m["paths"]["wiki"]
    # Enumerate real files so `mkdocs build --strict` never sees an unlisted page.
    # index.md is the homepage MkDocs serves at the site root.
    nav = ["  - Overview: index.md"]
    for tspec in m["page_types"].values():
        folder = tspec["folder"]
        files = sorted((wiki / folder).glob("*.md"))
        if not files:
            continue
        nav.append(f"  - {folder.capitalize()}:")
        for f in files:
            nav.append(f"      - {f.stem}: {folder}/{f.name}")
    return f"""# GENERATED by tools/viz.py from manifest.yaml. Do not hand-edit.
site_name: {m['name']!r}
site_description: {m['description'].strip()!r}
docs_dir: wiki
theme:
  name: material
  features: [navigation.instant, navigation.top, search.suggest, content.code.copy]
  palette:
    - scheme: default
      toggle: {{icon: material/brightness-7, name: dark}}
    - scheme: slate
      toggle: {{icon: material/brightness-4, name: light}}
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
nav:
{chr(10).join(nav)}
"""


def main() -> int:
    m = load_manifest()
    # The homepage (site root) is the knowledge graph itself.
    home_path = KB_ROOT / m["paths"]["wiki"] / "index.md"
    home_path.write_text("---\ntitle: Knowledge Graph\n---\n\n# Knowledge Graph\n\n"
                         "Nodes colored by confidence band. Regenerate with "
                         "`python tools/kb.py viz`.\n\n" + build_graph(m) + "\n")
    print(f"generated {home_path.relative_to(KB_ROOT)}")
    mk = KB_ROOT / "mkdocs.yml"
    mk.write_text(build_mkdocs(m))
    print(f"generated {mk.relative_to(KB_ROOT)}")
    print("build the site with:  cd .asdlc/knowledge && mkdocs build")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
